name: Terraform Validation

on:
  pull_request:
    branches: [main]
    paths:
      - 'terraform/**'

jobs:
  terraform-validate:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: terraform
        continue-on-error: true

      - name: Upload Terraform Plan
        if: steps.plan.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan-fail
          path: terraform/plan.out