name: CI/CD Pipeline

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - 'terraform/**'
  push:
    branches: [master]
    paths-ignore:
      - 'terraform/**'

jobs:
  build-test:
    name: Build and Test ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, users, todos]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go (for Auth API)
        if: matrix.service == 'auth'
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Set up Java (for Users API)
        if: matrix.service == 'users'
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Set up Node.js (for Todos API)
        if: matrix.service == 'todos'
        uses: actions/setup-node@v3
        with:
          node-version: '8.17.0'

      - name: Build ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}-api
          if [ "${{ matrix.service }}" = "users" ]; then
            ./mvnw clean package -DskipTests
          elif [ "${{ matrix.service }}" = "auth" ]; then
            go mod init github.com/bortizf/microservice-app-example/auth-api
            go mod tidy
            go build -o auth-service .
          elif [ "${{ matrix.service }}" = "todos" ]; then
            npm install
          fi

      - name: Test ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}-api
          if [ "${{ matrix.service }}" = "users" ]; then
            ./mvnw test
          elif [ "${{ matrix.service }}" = "auth" ]; then
            go test ./...
          elif [ "${{ matrix.service }}" = "todos" ]; then
            npm test
          fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'