name: Commit Policy Validation

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  validate-commit-policy:
    name: Validate Single Commit Policy
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Single Commit
        id: validate_commit
        run: |
          COMMIT_COUNT=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --oneline | wc -l)
          
          if [ "$COMMIT_COUNT" -ne 1 ]; then
            echo "❌ POLICY VIOLATION: This PR contains $COMMIT_COUNT commits. Enterprise policy requires exactly 1 commit per PR."
            exit 1
          fi
          
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          
          if [[ ! "$COMMIT_MESSAGE" =~ ^(feat|fix|chore|docs|test|refactor|perf|ci|build|revert)\([a-zA-Z0-9\-_]+\):[[:space:]].+ ]]; then
            echo "❌ POLICY VIOLATION: Commit message format must be 'type(component): description'"
            exit 1
          fi
          
          echo "✅ Commit policy validation passed"