name: Destroy Infrastructure (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      confirmation:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string

jobs:
  destroy-infrastructure:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: inputs.confirmation == 'DESTROY'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: terraform

      - name: Import Existing Resources (if needed)
        run: |
          chmod +x scripts/import_existing.sh
          ./scripts/import_existing.sh microservice-app-rg
        working-directory: terraform

      - name: Terraform Plan (Destroy)
        run: |
          terraform plan -destroy -input=false -no-color -out=destroy.tfplan
          terraform show -no-color destroy.tfplan > destroy-plan.txt
        working-directory: terraform

      - name: Terraform Destroy
        run: terraform apply -input=false -auto-approve destroy.tfplan
        working-directory: terraform

      - name: Verify Destruction
        run: |
          echo " Infrastructure destruction completed"
          echo "All resources have been removed from ${{ inputs.environment }}"
