- name: List Current State to Find Exact Resource Name
  run: |
    echo "🔍 Current resources in Terraform state:"
    terraform state list
  working-directory: ./terraform
  env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

- name: Remove Corrupted PostgreSQL State (if exists)
  run: |
    echo "🧹 Attempting to remove PostgreSQL state entry..."
    # Busca el nombre exacto
    STATE_ENTRY=$(terraform state list | grep "postgresql_flexible_server" | head -n1)
    if [ -n "$STATE_ENTRY" ]; then
      echo "🗑️ Found: $STATE_ENTRY → Removing..."
      terraform state rm "$STATE_ENTRY"
    else
      echo "✅ No PostgreSQL Flexible Server found in state. Nothing to remove."
    fi
  working-directory: ./terraform
  env:
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
