name: Staging Environment Cleanup

on:
  schedule:
    # Ejecutar cleanup diario a las 2 AM UTC (antes del horario de trabajo)
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  cleanup-staging:
    name: Cleanup Staging Resources
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: terraform

      - name: Check for Resources
        run: |
          if terraform state list | grep -q .; then
            echo "Resources found, proceeding with cleanup"
            echo "CLEANUP_NEEDED=true" >> $GITHUB_ENV
          else
            echo "No resources to clean up"
            echo "CLEANUP_NEEDED=false" >> $GITHUB_ENV
          fi
        working-directory: terraform

      - name: Terraform Destroy (if resources exist)
        if: env.CLEANUP_NEEDED == 'true'
        run: terraform destroy -input=false -auto-approve
        working-directory: terraform

      - name: Cleanup Complete
        run: |
          echo "✅ Staging environment cleanup completed"
          echo "All temporary resources have been removed"
